id: P003068
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:38:16.257695
source_metadata:
  id: bdr:W8LS20516
  title: བོད་དཔྱད་སྤྱི་རྒྱ་རླབས་གཅོད།
  author: ''
  volumes:
    f91e70b1f3d14209bacd3661a3484b14:
      image_group_id: I8LS20518
      title: ''
      volume_number: 1
      total_pages: 500
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
