id: I1DD468FE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:30:45+00:00'
last_modified: '2022-06-07T17:20:29.144150+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20516
  title: བོད་དཔྱད་སྤྱི་རྒྱ་རླབས་གཅོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    648B:
      image_group_id: I8LS20518
      title: ''
      total_pages: 500
      order: 1
      base_file: 648B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
